kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ONBOARD_ORG: {{.Values.onboard.org}}
  ONBOARD_REPO: {{.Values.onboard.repo}}
